zcashd:
  enabled: False
  name: zcashd
  testnet: False
  image:
    repository: electriccoinco/zcashd
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  reindex: False
  nodes:
   - mainnet.z.cash
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
      storageClass: default
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi
  #limits:
  #  memory: 3Gi

zebra:
  enabled: True
  name: zebra
  testnet: false
  image:
    repository: zfnd/zebra
    tag: v1.9.0
    pullPolicy: IfNotPresent
  replicas: 1
  additionalEnv: {}
  volumes:
    data:
      size: 400Gi
      storageClass: default
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 2
  #   memory: 4Gi
  # limits:
  #   memory: 16Gi

rpc:
  credentials:
    rpcUser: 5s3rn4m3
    rpcPassword: s3cr3tp4ssw0rd

lightwalletd:
  enabled: true
  zcashNodeType: zebra # zebra or zcashd
  name: lightwalletd
  image:
    repository: electriccoinco/lightwalletd
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
      storageClass: default
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 0.5
  #   memory: 512Mi
  #limits:
  #  memory: 3Gi

# lightwalletd-front
caddy: 
  enabled: False
  domain: "lwd.example.com"
  email: "admin@example.com"

dnsseeder:
  enabled: True
  name: dnsseeder
  replicas: 1
  image:
    repository: electriccoinco/dnsseeder
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi
  #limits:
  #  memory: 3Gi
  env:
    seedHostname: "example.com"
    nodeHostname: "zcash.example.com"
    email: "admin@example.com"
    threads: 384
    address: "0.0.0.0"
    network: "mainnet"
