{{- if .Values.caddy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-caddy
data:
  Caddyfile: |
    {{- if .Values.lightwalletd.enabled }}
    {{ .Values.caddy.domainLightwalletd }} {
        reverse_proxy h2c://{{ .Release.Name }}-{{ .Values.lightwalletd.name }}:9067
        tls {{ .Values.caddy.email }}
    }
    {{- end }}
    {{- if and .Values.zfaucet.enabled .Values.zcashd.enabled }}
    {{ .Values.caddy.domainZfaucet }} {
        reverse_proxy h2c://{{ .Release.Name }}-{{ .Values.zfaucet.name }}:8000
        tls {{ .Values.caddy.email }}
    }
    {{- end }}
{{- end }}
