{{- if .Values.caddy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-caddy
spec:
  selector:
    app: {{ .Release.Name }}-caddy
  ports:
    - protocol: TCP
      port: 80       # Puerto HTTP
      targetPort: 80
      name: http     # Nombre del puerto HTTP
    - protocol: TCP
      port: 443      # Puerto HTTPS
      targetPort: 443
      name: https    # Nombre del puerto HTTPS
  type: LoadBalancer
{{- end }}