{{- if .Values.caddy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-caddy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-caddy
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-config
          configMap:
            name: {{ .Release.Name }}-caddy
{{- end }}