{{- if .Values.lightwalletd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.lightwalletd.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.lightwalletd.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.lightwalletd.name }}
  ports:
    - name: http
      protocol: TCP
      port: 9067
      targetPort: 9067
  type: {{ .Values.lightwalletd.service.type }}
{{- end }}

