{{- if .Values.zcashd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.zcashd.name }}
spec:
  type: {{ .Values.zcashd.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.zcashd.name }}
  ports:
    - port: 8232
      targetPort: 8232
      protocol: TCP
      name: rpc
{{- end }}
