name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Extract repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Create Helm package
        run: |
          helm package .
          mkdir -p "${RUNNER_TEMP}/helm-repo"
          mv *.tgz "${RUNNER_TEMP}/helm-repo/"

      - name: Update Helm repo index
        run: |
          helm repo index . --url "https://${GITHUB_ACTOR}.github.io/${REPO_NAME}/"
          if [ -f ./index.yaml ]; then
            helm repo index . --merge ./index.yaml --url "https://${GITHUB_ACTOR}.github.io/${REPO_NAME}/"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: helm-repo
          publish_branch: gh-pages
